language: node_js

# Safelist
branches:
  only:
    - master

jobs:
  include:
    - stage: install
      script: cd app & npm install
    - stage: build
      script: cd app & npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master