language: node_js
node_js:
  - "node"

cache: npm

# Safelist
branches:
  only:
    - master

script: cd app & npm install

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master