name: Run Build and Test Automation
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Install 🔧 # This runs a series of commands as if building a live version of the project
        run: |
          yarn

      - name: Build 🔧 # This runs a series of commands as if building a live version of the project
        run: |
          yarn build
